apiVersion: 1
prune: true

datasources:
  - name: WM ClickHouse Telemetry Store
    uid: idp-telemetry-store-telemetry-store
    type: grafana-clickhouse-datasource
    access: proxy
    orgId: 1
    isDefault: true
    editable: false
    version: 1
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: ${CLICKHOUSE_DATABASE}
      username: ${CLICKHOUSE_USER}
      tlsSkipVerify: false
      secure: false
      dialTimeout: 10
      queryTimeout: 60
      validateSql: true
      enableRowLimit: true
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
